### ISSUE TITLE
Custom Command: Update oder Shutdown

### ISSUE THREAD

**Issue by Edocsyl** [IGEL-Community/IGEL-Community.github.io#2]
Im Case ITRS#2020090810001091 haben wir darüber diskutiert, dass bei einem Custom Shutdown Command der Igel nicht aktualsieirt, obwoh die Einstellung "Update Prüfen bei Herunterfahren" aktiv ist. Anhang von vorhandnene Custom kommands, habe ich für das OS10 & 11 Custom Commands geschrieben, welche Prüfen, ob ein Update vorhanden ist und wenn ja, dann wird es installiert, ansonsten wird "forciert" heruntergefahren: 

**OS11**
`CURRENT=$(cat /etc/os-release | grep VERSION= | egrep -o "([0-9]{1,}\.)+[0-9]{1,}") && NEW=$(cat /wfs/group.ini | grep IGEL_OS_11 | egrep -o "([0-9]{1,}\.)+[0-9]{1,}") && if [ $CURRENT !=  $NEW ]; then /config/bin/firmware-update; else /sbin/user_shutdown -f; fi`

**OS10**
`CURRENT=$(cat /etc/os-release | grep VERSION= | egrep -o "([0-9]{1,}\.)+[0-9]{1,}") && NEW=$(cat /wfs/group.ini | grep IGEL_Universal_Desktop | egrep -o "([0-9]{1,}\.)+[0-9]{1,}") && if [ $CURRENT !=  $NEW ]; then /config/bin/firmware-update; else /sbin/user_shutdown -f; fi`

Können Sie diese diese Commands gegenprüfen und ins Wiki aufnehmen?

**Comment by falkheiland** [comment]
thx for the input! i will open an issue in a soon to be published new repo.
this repo will be closed - so does the issue.
